//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.2615.1
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=1.0.2615.1.
// 
namespace TheCalcProxy
{
	using System.Xml.Serialization;
	using System;
	using System.Web.Services.Protocols;
	using System.Web.Services;


	[System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
	public class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol 
	{
    
		public Service1() 
		{
			this.Url = "http://localhost/calcwebservice/calcservice.asmx";
		}
    
		[System.Web.Services.Protocols.SoapMethodAttribute("http://tempuri.org/Add", MessageStyle=System.Web.Services.Protocols.SoapMessageStyle.ParametersInDocument)]
		public int Add(int x, int y) 
		{
			object[] results = this.Invoke("Add", new object[] {x,
																   y});
			return ((int)(results[0]));
		}
    
		public System.IAsyncResult BeginAdd(int x, int y, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("Add", new object[] {x,
															y}, callback, asyncState);
		}
    
		public int EndAdd(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((int)(results[0]));
		}
    
		[System.Web.Services.WebMethodAttribute(MessageName="Add1")]
		[System.Web.Services.Protocols.SoapMethodAttribute("http://tempuri.org/AddFloats", RequestElementName="AddFloats", ResponseElementName="AddFloatsResponse", MessageStyle=System.Web.Services.Protocols.SoapMessageStyle.ParametersInDocument)]
		[return: System.Xml.Serialization.XmlElementAttribute("AddFloatsResult", IsNullable=false)]
		public System.Single Add(System.Single x, System.Single y) 
		{
			object[] results = this.Invoke("Add1", new object[] {x,
																	y});
			return ((System.Single)(results[0]));
		}
    
		public System.IAsyncResult BeginAdd1(System.Single x, System.Single y, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("Add1", new object[] {x,
															 y}, callback, asyncState);
		}
    
		public System.Single EndAdd1(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Single)(results[0]));
		}
    
		[System.Web.Services.Protocols.SoapMethodAttribute("http://tempuri.org/Subtract", MessageStyle=System.Web.Services.Protocols.SoapMessageStyle.ParametersInDocument)]
		public int Subtract(int x, int y) 
		{
			object[] results = this.Invoke("Subtract", new object[] {x,
																		y});
			return ((int)(results[0]));
		}
    
		public System.IAsyncResult BeginSubtract(int x, int y, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("Subtract", new object[] {x,
																 y}, callback, asyncState);
		}
    
		public int EndSubtract(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((int)(results[0]));
		}
    
		[System.Web.Services.Protocols.SoapMethodAttribute("http://tempuri.org/Multiply", MessageStyle=System.Web.Services.Protocols.SoapMessageStyle.ParametersInDocument)]
		public int Multiply(int x, int y) 
		{
			object[] results = this.Invoke("Multiply", new object[] {x,
																		y});
			return ((int)(results[0]));
		}
    
		public System.IAsyncResult BeginMultiply(int x, int y, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("Multiply", new object[] {x,
																 y}, callback, asyncState);
		}
    
		public int EndMultiply(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((int)(results[0]));
		}
    
		[System.Web.Services.Protocols.SoapMethodAttribute("http://tempuri.org/Divide", MessageStyle=System.Web.Services.Protocols.SoapMessageStyle.ParametersInDocument)]
		public int Divide(int x, int y) 
		{
			object[] results = this.Invoke("Divide", new object[] {x,
																	  y});
			return ((int)(results[0]));
		}
    
		public System.IAsyncResult BeginDivide(int x, int y, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("Divide", new object[] {x,
															   y}, callback, asyncState);
		}
    
		public int EndDivide(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((int)(results[0]));
		}
    
		[System.Web.Services.Protocols.SoapMethodAttribute("http://tempuri.org/GetSimplePI", MessageStyle=System.Web.Services.Protocols.SoapMessageStyle.ParametersInDocument)]
		public System.Single GetSimplePI() 
		{
			object[] results = this.Invoke("GetSimplePI", new object[0]);
			return ((System.Single)(results[0]));
		}
    
		public System.IAsyncResult BeginGetSimplePI(System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("GetSimplePI", new object[0], callback, asyncState);
		}
    
		public System.Single EndGetSimplePI(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((System.Single)(results[0]));
		}
	}
}
